"""add_segment_to_auto_trade_execution

Revision ID: 010a2fc40ed1
Revises: 1c2182e0aa07
Create Date: 2026-02-09 16:21:08.448321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '010a2fc40ed1'
down_revision: Union[str, None] = '1c2182e0aa07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auto_trade_executions', sa.Column('segment', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_auto_trade_executions_segment'), 'auto_trade_executions', ['segment'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auto_trade_executions_segment'), table_name='auto_trade_executions')
    op.drop_column('auto_trade_executions', 'segment')
    # ### end Alembic commands ###
