"""Added new columns to models

Revision ID: 0b6c9c8c2846
Revises: 05dd12f64da0
Create Date: 2025-05-23 23:11:55.884131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b6c9c8c2846'
down_revision: Union[str, None] = '05dd12f64da0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('provider_email', sa.String(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_auth_id'), 'social_auth', ['id'], unique=False)
    op.create_index('ix_social_auth_provider_id', 'social_auth', ['provider', 'provider_id'], unique=True)
    op.add_column('otp_codes', sa.Column('email', sa.String(), nullable=True))
    op.add_column('otp_codes', sa.Column('verification_method', sa.String(), nullable=True))
    op.add_column('otp_codes', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('otp_codes', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('otp_codes', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.execute('ALTER TABLE otp_codes DROP CONSTRAINT IF EXISTS otp_codes_phone_number_key')
    op.add_column('users', sa.Column('phone_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('google_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('auth_provider', sa.String(), nullable=True))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_unique_constraint(None, 'users', ['google_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'auth_provider')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'google_id')
    op.drop_column('users', 'phone_verified')
    op.create_unique_constraint('otp_codes_phone_number_key', 'otp_codes', ['phone_number'])
    op.alter_column('otp_codes', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('otp_codes', 'created_at')
    op.drop_column('otp_codes', 'is_verified')
    op.drop_column('otp_codes', 'verification_method')
    op.drop_column('otp_codes', 'email')
    op.drop_index('ix_social_auth_provider_id', table_name='social_auth')
    op.drop_index(op.f('ix_social_auth_id'), table_name='social_auth')
    op.drop_table('social_auth')
    # ### end Alembic commands ###
