"""add_strike_price_to_auto_trade_execution

Revision ID: 222b77b126d9
Revises: d4b665073e28
Create Date: 2026-01-29 21:49:06.496989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '222b77b126d9'
down_revision: Union[str, None] = 'd4b665073e28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auto_trade_executions', sa.Column('strike_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('fno_stock_metadata', sa.Column('lots_traded', sa.Integer(), nullable=True))
    op.add_column('fno_stock_metadata', sa.Column('total_investment', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('paper_trading_positions', sa.Column('lots_traded', sa.Integer(), nullable=True))
    op.add_column('paper_trading_positions', sa.Column('total_investment', sa.Numeric(precision=15, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper_trading_positions', 'total_investment')
    op.drop_column('paper_trading_positions', 'lots_traded')
    op.drop_column('fno_stock_metadata', 'total_investment')
    op.drop_column('fno_stock_metadata', 'lots_traded')
    op.drop_column('auto_trade_executions', 'strike_price')
    # ### end Alembic commands ###
