"""add_expiry_date_to_auto_trade_execution

Revision ID: 2bbf0919f16c
Revises: 010a2fc40ed1
Create Date: 2026-02-13 16:54:02.831762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bbf0919f16c'
down_revision: Union[str, None] = '010a2fc40ed1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auto_trade_executions', sa.Column('expiry_date', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auto_trade_executions', 'expiry_date')
    # ### end Alembic commands ###
