"""Add trading_mode and execution_mode to UserTradingConfig

Revision ID: 5d88855a7fd3
Revises: cf6126e17b1b
Create Date: 2025-10-05 12:51:05.796227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d88855a7fd3'
down_revision: Union[str, None] = 'cf6126e17b1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_trading_config', sa.Column('trading_mode', sa.String(length=20), nullable=True))
    op.add_column('user_trading_config', sa.Column('execution_mode', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_user_trading_config_execution_mode'), 'user_trading_config', ['execution_mode'], unique=False)
    op.create_index(op.f('ix_user_trading_config_trading_mode'), 'user_trading_config', ['trading_mode'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_trading_config_trading_mode'), table_name='user_trading_config')
    op.drop_index(op.f('ix_user_trading_config_execution_mode'), table_name='user_trading_config')
    op.drop_column('user_trading_config', 'execution_mode')
    op.drop_column('user_trading_config', 'trading_mode')
    # ### end Alembic commands ###
