"""add feed_token to broker_configs

Revision ID: 62fdb5505a5b
Revises: a9efee0bc74f
Create Date: 2025-07-06 21:59:34.812793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62fdb5505a5b'
down_revision: Union[str, None] = 'a9efee0bc74f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('broker_configs', sa.Column('feed_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('broker_configs', 'feed_token')
    # ### end Alembic commands ###
