"""Add premarket candle and gap detection tables

Revision ID: 65096d87f51c
Revises: cb6244cae710
Create Date: 2025-09-07 15:48:13.117254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65096d87f51c'
down_revision: Union[str, None] = 'cb6244cae710'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('premarket_candles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('instrument_key', sa.String(length=100), nullable=False),
    sa.Column('exchange', sa.String(length=10), nullable=True),
    sa.Column('candle_date', sa.Date(), nullable=False),
    sa.Column('candle_start_time', sa.DateTime(), nullable=False),
    sa.Column('candle_end_time', sa.DateTime(), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('high_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('low_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_volume', sa.BigInteger(), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('avg_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('previous_close', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gap_percentage', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('gap_type', sa.String(length=10), nullable=True),
    sa.Column('gap_strength', sa.String(length=15), nullable=True),
    sa.Column('volume_ratio', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('volume_confirmation', sa.Boolean(), nullable=True),
    sa.Column('ticks_received', sa.Integer(), nullable=True),
    sa.Column('data_quality_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('sector', sa.String(length=50), nullable=True),
    sa.Column('market_cap_category', sa.String(length=15), nullable=True),
    sa.Column('is_significant_gap', sa.Boolean(), nullable=True),
    sa.Column('processed_by_strategy', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("gap_strength IN ('WEAK', 'MODERATE', 'STRONG', 'VERY_STRONG')", name='ck_valid_gap_strength'),
    sa.CheckConstraint("gap_type IN ('GAP_UP', 'GAP_DOWN', 'NO_GAP')", name='ck_valid_gap_type'),
    sa.CheckConstraint('data_quality_score >= 0 AND data_quality_score <= 1', name='ck_quality_score_range'),
    sa.CheckConstraint('gap_percentage >= -50 AND gap_percentage <= 50', name='ck_gap_percentage_range'),
    sa.CheckConstraint('high_price >= low_price', name='ck_high_low_price'),
    sa.CheckConstraint('high_price >= open_price AND high_price >= close_price', name='ck_high_price_validity'),
    sa.CheckConstraint('low_price <= open_price AND low_price <= close_price', name='ck_low_price_validity'),
    sa.CheckConstraint('volume_ratio >= 0', name='ck_positive_volume_ratio'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_key', 'candle_date', name='uq_premarket_instrument_date')
    )
    op.create_index('idx_premarket_date_gap', 'premarket_candles', ['candle_date', 'is_significant_gap', 'gap_type'], unique=False)
    op.create_index('idx_premarket_gap_analysis', 'premarket_candles', ['gap_strength', 'volume_confirmation', 'sector'], unique=False)
    op.create_index('idx_premarket_instrument_date', 'premarket_candles', ['instrument_key', 'candle_date'], unique=False)
    op.create_index('idx_premarket_quality', 'premarket_candles', ['data_quality_score', 'ticks_received'], unique=False)
    op.create_index('idx_premarket_symbol_date', 'premarket_candles', ['symbol', 'candle_date'], unique=False)
    op.create_index(op.f('ix_premarket_candles_candle_date'), 'premarket_candles', ['candle_date'], unique=False)
    op.create_index(op.f('ix_premarket_candles_id'), 'premarket_candles', ['id'], unique=False)
    op.create_index(op.f('ix_premarket_candles_instrument_key'), 'premarket_candles', ['instrument_key'], unique=False)
    op.create_index(op.f('ix_premarket_candles_is_significant_gap'), 'premarket_candles', ['is_significant_gap'], unique=False)
    op.create_index(op.f('ix_premarket_candles_symbol'), 'premarket_candles', ['symbol'], unique=False)
    op.create_table('gap_detection_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('premarket_candle_id', sa.Integer(), nullable=True),
    sa.Column('alert_time', sa.DateTime(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('gap_percentage', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('gap_type', sa.String(length=10), nullable=False),
    sa.Column('gap_strength', sa.String(length=15), nullable=False),
    sa.Column('trigger_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('previous_close', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('alert_priority', sa.String(length=10), nullable=True),
    sa.Column('alert_status', sa.String(length=15), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('volume_at_alert', sa.BigInteger(), nullable=True),
    sa.Column('volume_ratio', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('processed_by_trading_system', sa.Boolean(), nullable=True),
    sa.CheckConstraint("alert_priority IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')", name='ck_alert_priority'),
    sa.CheckConstraint("alert_status IN ('ACTIVE', 'ACKNOWLEDGED', 'EXPIRED')", name='ck_alert_status'),
    sa.CheckConstraint("gap_type IN ('GAP_UP', 'GAP_DOWN')", name='ck_alert_gap_type'),
    sa.CheckConstraint('confidence_score >= 0 AND confidence_score <= 1', name='ck_alert_confidence_range'),
    sa.ForeignKeyConstraint(['premarket_candle_id'], ['premarket_candles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_gap_alert_active', 'gap_detection_alerts', ['alert_status', 'alert_time'], unique=False)
    op.create_index('idx_gap_alert_priority', 'gap_detection_alerts', ['alert_priority', 'confidence_score'], unique=False)
    op.create_index('idx_gap_alert_processing', 'gap_detection_alerts', ['processed_by_trading_system', 'alert_status'], unique=False)
    op.create_index('idx_gap_alert_symbol', 'gap_detection_alerts', ['symbol', 'gap_type', 'alert_time'], unique=False)
    op.create_index(op.f('ix_gap_detection_alerts_alert_time'), 'gap_detection_alerts', ['alert_time'], unique=False)
    op.create_index(op.f('ix_gap_detection_alerts_id'), 'gap_detection_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_gap_detection_alerts_premarket_candle_id'), 'gap_detection_alerts', ['premarket_candle_id'], unique=False)
    op.create_index(op.f('ix_gap_detection_alerts_symbol'), 'gap_detection_alerts', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gap_detection_alerts_symbol'), table_name='gap_detection_alerts')
    op.drop_index(op.f('ix_gap_detection_alerts_premarket_candle_id'), table_name='gap_detection_alerts')
    op.drop_index(op.f('ix_gap_detection_alerts_id'), table_name='gap_detection_alerts')
    op.drop_index(op.f('ix_gap_detection_alerts_alert_time'), table_name='gap_detection_alerts')
    op.drop_index('idx_gap_alert_symbol', table_name='gap_detection_alerts')
    op.drop_index('idx_gap_alert_processing', table_name='gap_detection_alerts')
    op.drop_index('idx_gap_alert_priority', table_name='gap_detection_alerts')
    op.drop_index('idx_gap_alert_active', table_name='gap_detection_alerts')
    op.drop_table('gap_detection_alerts')
    op.drop_index(op.f('ix_premarket_candles_symbol'), table_name='premarket_candles')
    op.drop_index(op.f('ix_premarket_candles_is_significant_gap'), table_name='premarket_candles')
    op.drop_index(op.f('ix_premarket_candles_instrument_key'), table_name='premarket_candles')
    op.drop_index(op.f('ix_premarket_candles_id'), table_name='premarket_candles')
    op.drop_index(op.f('ix_premarket_candles_candle_date'), table_name='premarket_candles')
    op.drop_index('idx_premarket_symbol_date', table_name='premarket_candles')
    op.drop_index('idx_premarket_quality', table_name='premarket_candles')
    op.drop_index('idx_premarket_instrument_date', table_name='premarket_candles')
    op.drop_index('idx_premarket_gap_analysis', table_name='premarket_candles')
    op.drop_index('idx_premarket_date_gap', table_name='premarket_candles')
    op.drop_table('premarket_candles')
    # ### end Alembic commands ###
