"""add_execution_notes_to_auto_trade_execution

Revision ID: 762a64d64b9d
Revises: 2bbf0919f16c
Create Date: 2026-02-23 11:45:05.510175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '762a64d64b9d'
down_revision: Union[str, None] = '2bbf0919f16c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auto_trade_executions', sa.Column('execution_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auto_trade_executions', 'execution_notes')
    # ### end Alembic commands ###
