"""add_email_and_otp_type_to_otp_table

Revision ID: 796cb6171601
Revises: 6292d90c2d59
Create Date: 2025-05-24 23:36:56.999580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '796cb6171601'
down_revision: Union[str, None] = '6292d90c2d59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
