"""Add F&O stock metadata and selection history tables for Phase 2

Revision ID: 7ddbb769ef69
Revises: 8d698efd7ec5
Create Date: 2025-08-25 16:16:02.541496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ddbb769ef69'
down_revision: Union[str, None] = '8d698efd7ec5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fno_stock_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=True),
    sa.Column('sector', sa.String(length=50), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('index_membership', sa.JSON(), nullable=False),
    sa.Column('primary_index', sa.String(length=20), nullable=True),
    sa.Column('lot_size', sa.Integer(), nullable=False),
    sa.Column('tick_size', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('instrument_type', sa.String(length=20), nullable=True),
    sa.Column('avg_daily_volume', sa.BigInteger(), nullable=True),
    sa.Column('market_cap', sa.BigInteger(), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_change_percent', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('option_liquidity_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('ce_liquidity_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('pe_liquidity_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('liquid_strikes_count', sa.Integer(), nullable=True),
    sa.Column('total_option_oi', sa.BigInteger(), nullable=True),
    sa.Column('fibonacci_respect_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('swing_clarity_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('ema_alignment_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('overall_fibonacci_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('volatility_30d', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('avg_true_range', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('beta_vs_nifty', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('correlation_nifty', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('times_selected', sa.Integer(), nullable=True),
    sa.Column('last_selected_date', sa.Date(), nullable=True),
    sa.Column('selection_success_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('avg_holding_period_hours', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('is_active_fno', sa.Boolean(), nullable=True),
    sa.Column('quality_grade', sa.String(length=2), nullable=True),
    sa.Column('is_fibonacci_friendly', sa.Boolean(), nullable=True),
    sa.Column('last_liquidity_check', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_analysis_date', sa.Date(), nullable=True),
    sa.CheckConstraint("quality_grade IN ('A+', 'A', 'B+', 'B', 'C')", name='ck_valid_quality_grade'),
    sa.CheckConstraint('fibonacci_respect_score >= 0 AND fibonacci_respect_score <= 1', name='ck_fib_respect_range'),
    sa.CheckConstraint('lot_size > 0', name='ck_positive_lot_size'),
    sa.CheckConstraint('option_liquidity_score >= 0 AND option_liquidity_score <= 1', name='ck_option_liquidity_range'),
    sa.CheckConstraint('selection_success_rate >= 0 AND selection_success_rate <= 100', name='ck_success_rate_range'),
    sa.CheckConstraint('swing_clarity_score >= 0 AND swing_clarity_score <= 1', name='ck_swing_clarity_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fno_active_quality', 'fno_stock_metadata', ['is_active_fno', 'quality_grade', 'primary_index'], unique=False)
    op.create_index('idx_fno_fibonacci_selection', 'fno_stock_metadata', ['is_fibonacci_friendly', 'overall_fibonacci_score', 'option_liquidity_score'], unique=False)
    op.create_index('idx_fno_liquidity', 'fno_stock_metadata', ['option_liquidity_score', 'liquid_strikes_count', 'total_option_oi'], unique=False)
    op.create_index('idx_fno_performance', 'fno_stock_metadata', ['times_selected', 'selection_success_rate', 'last_selected_date'], unique=False)
    op.create_index('idx_fno_sector_index', 'fno_stock_metadata', ['sector', 'primary_index', 'market_cap'], unique=False)
    op.create_index('idx_fno_volatility', 'fno_stock_metadata', ['volatility_30d', 'avg_true_range', 'beta_vs_nifty'], unique=False)
    op.create_index(op.f('ix_fno_stock_metadata_avg_daily_volume'), 'fno_stock_metadata', ['avg_daily_volume'], unique=False)
    op.create_index(op.f('ix_fno_stock_metadata_ema_alignment_score'), 'fno_stock_metadata', ['ema_alignment_score'], unique=False)
    op.create_index(op.f('ix_fno_stock_metadata_fibonacci_respect_score'), 'fno_stock_metadata', ['fibonacci_respect_score'], unique=False)
    op.create_index(op.f('ix_fno_stock_metadata_id'), 'fno_stock_metadata', ['id'], unique=False)
    op.create_index(op.f('ix_fno_stock_metadata_is_active_fno'), 'fno_stock_metadata', ['is_active_fno'], unique=False)
    op.create_index(op.f('ix_fno_stock_metadata_is_fibonacci_friendly'), 'fno_stock_metadata', ['is_fibonacci_friendly'], unique=False)
    op.create_index(op.f('ix_fno_stock_metadata_option_liquidity_score'), 'fno_stock_metadata', ['option_liquidity_score'], unique=False)
    op.create_index(op.f('ix_fno_stock_metadata_overall_fibonacci_score'), 'fno_stock_metadata', ['overall_fibonacci_score'], unique=False)
    op.create_index(op.f('ix_fno_stock_metadata_primary_index'), 'fno_stock_metadata', ['primary_index'], unique=False)
    op.create_index(op.f('ix_fno_stock_metadata_quality_grade'), 'fno_stock_metadata', ['quality_grade'], unique=False)
    op.create_index(op.f('ix_fno_stock_metadata_sector'), 'fno_stock_metadata', ['sector'], unique=False)
    op.create_index(op.f('ix_fno_stock_metadata_swing_clarity_score'), 'fno_stock_metadata', ['swing_clarity_score'], unique=False)
    op.create_index(op.f('ix_fno_stock_metadata_symbol'), 'fno_stock_metadata', ['symbol'], unique=True)
    op.create_table('fno_selection_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('selection_date', sa.Date(), nullable=False),
    sa.Column('selection_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_type', sa.String(length=20), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('selection_score', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('selection_rank', sa.Integer(), nullable=True),
    sa.Column('market_sentiment', sa.String(length=20), nullable=True),
    sa.Column('nifty_change_percent', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('sector_momentum', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('fibonacci_levels_at_selection', sa.JSON(), nullable=True),
    sa.Column('ema_values_at_selection', sa.JSON(), nullable=True),
    sa.Column('price_at_selection', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('technical_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('liquidity_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('market_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('option_type_selected', sa.String(length=5), nullable=True),
    sa.Column('atm_strike', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('option_premium', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('option_liquidity', sa.JSON(), nullable=True),
    sa.Column('was_traded', sa.Boolean(), nullable=True),
    sa.Column('trade_outcome', sa.String(length=20), nullable=True),
    sa.Column('profit_loss_points', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('profit_loss_percent', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('holding_period_minutes', sa.Integer(), nullable=True),
    sa.Column('max_favorable_move', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('max_adverse_move', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('fibonacci_level_accuracy', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('trade_closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('selection_date', 'symbol', 'user_id', name='uq_daily_stock_selection')
    )
    op.create_index('idx_selection_history_date', 'fno_selection_history', ['selection_date', 'symbol'], unique=False)
    op.create_index('idx_selection_history_market', 'fno_selection_history', ['market_sentiment', 'session_type', 'selection_date'], unique=False)
    op.create_index('idx_selection_history_strategy', 'fno_selection_history', ['fibonacci_level_accuracy', 'profit_loss_percent', 'holding_period_minutes'], unique=False)
    op.create_index('idx_selection_history_symbol', 'fno_selection_history', ['symbol', 'was_traded', 'trade_outcome'], unique=False)
    op.create_index('idx_selection_history_user', 'fno_selection_history', ['user_id', 'selection_date', 'trade_outcome'], unique=False)
    op.create_index(op.f('ix_fno_selection_history_id'), 'fno_selection_history', ['id'], unique=False)
    op.create_index(op.f('ix_fno_selection_history_selection_date'), 'fno_selection_history', ['selection_date'], unique=False)
    op.create_index(op.f('ix_fno_selection_history_symbol'), 'fno_selection_history', ['symbol'], unique=False)
    op.create_index(op.f('ix_fno_selection_history_user_id'), 'fno_selection_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fno_selection_history_user_id'), table_name='fno_selection_history')
    op.drop_index(op.f('ix_fno_selection_history_symbol'), table_name='fno_selection_history')
    op.drop_index(op.f('ix_fno_selection_history_selection_date'), table_name='fno_selection_history')
    op.drop_index(op.f('ix_fno_selection_history_id'), table_name='fno_selection_history')
    op.drop_index('idx_selection_history_user', table_name='fno_selection_history')
    op.drop_index('idx_selection_history_symbol', table_name='fno_selection_history')
    op.drop_index('idx_selection_history_strategy', table_name='fno_selection_history')
    op.drop_index('idx_selection_history_market', table_name='fno_selection_history')
    op.drop_index('idx_selection_history_date', table_name='fno_selection_history')
    op.drop_table('fno_selection_history')
    op.drop_index(op.f('ix_fno_stock_metadata_symbol'), table_name='fno_stock_metadata')
    op.drop_index(op.f('ix_fno_stock_metadata_swing_clarity_score'), table_name='fno_stock_metadata')
    op.drop_index(op.f('ix_fno_stock_metadata_sector'), table_name='fno_stock_metadata')
    op.drop_index(op.f('ix_fno_stock_metadata_quality_grade'), table_name='fno_stock_metadata')
    op.drop_index(op.f('ix_fno_stock_metadata_primary_index'), table_name='fno_stock_metadata')
    op.drop_index(op.f('ix_fno_stock_metadata_overall_fibonacci_score'), table_name='fno_stock_metadata')
    op.drop_index(op.f('ix_fno_stock_metadata_option_liquidity_score'), table_name='fno_stock_metadata')
    op.drop_index(op.f('ix_fno_stock_metadata_is_fibonacci_friendly'), table_name='fno_stock_metadata')
    op.drop_index(op.f('ix_fno_stock_metadata_is_active_fno'), table_name='fno_stock_metadata')
    op.drop_index(op.f('ix_fno_stock_metadata_id'), table_name='fno_stock_metadata')
    op.drop_index(op.f('ix_fno_stock_metadata_fibonacci_respect_score'), table_name='fno_stock_metadata')
    op.drop_index(op.f('ix_fno_stock_metadata_ema_alignment_score'), table_name='fno_stock_metadata')
    op.drop_index(op.f('ix_fno_stock_metadata_avg_daily_volume'), table_name='fno_stock_metadata')
    op.drop_index('idx_fno_volatility', table_name='fno_stock_metadata')
    op.drop_index('idx_fno_sector_index', table_name='fno_stock_metadata')
    op.drop_index('idx_fno_performance', table_name='fno_stock_metadata')
    op.drop_index('idx_fno_liquidity', table_name='fno_stock_metadata')
    op.drop_index('idx_fno_fibonacci_selection', table_name='fno_stock_metadata')
    op.drop_index('idx_fno_active_quality', table_name='fno_stock_metadata')
    op.drop_table('fno_stock_metadata')
    # ### end Alembic commands ###
