"""Add auto trading performance and monitoring tables

Revision ID: 8d698efd7ec5
Revises: 62fdb5505a5b
Create Date: 2025-08-25 15:17:43.436594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d698efd7ec5'
down_revision: Union[str, None] = '62fdb5505a5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_trading_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trading_date', sa.Date(), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('winning_trades', sa.Integer(), nullable=True),
    sa.Column('losing_trades', sa.Integer(), nullable=True),
    sa.Column('breakeven_trades', sa.Integer(), nullable=True),
    sa.Column('gross_pnl', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('net_pnl', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('largest_win', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('largest_loss', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('win_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('avg_win', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('avg_loss', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('profit_factor', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('expectancy', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('max_consecutive_losses', sa.Integer(), nullable=True),
    sa.Column('max_consecutive_wins', sa.Integer(), nullable=True),
    sa.Column('sharpe_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('fibonacci_signals_generated', sa.Integer(), nullable=True),
    sa.Column('fibonacci_signals_executed', sa.Integer(), nullable=True),
    sa.Column('signal_to_execution_ratio', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('account_balance_start', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('account_balance_end', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('daily_return_percentage', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'trading_date', name='uq_daily_perf_user_date')
    )
    op.create_index('idx_daily_perf_date', 'daily_trading_performance', ['trading_date'], unique=False)
    op.create_index(op.f('ix_daily_trading_performance_id'), 'daily_trading_performance', ['id'], unique=False)
    op.create_index(op.f('ix_daily_trading_performance_trading_date'), 'daily_trading_performance', ['trading_date'], unique=False)
    op.create_table('emergency_controls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('control_type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('max_daily_loss', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('max_consecutive_losses', sa.Integer(), nullable=True),
    sa.Column('max_drawdown_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('max_position_count', sa.Integer(), nullable=True),
    sa.Column('current_daily_loss', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('current_consecutive_losses', sa.Integer(), nullable=True),
    sa.Column('current_drawdown', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('current_position_count', sa.Integer(), nullable=True),
    sa.Column('emergency_triggered', sa.Boolean(), nullable=True),
    sa.Column('trigger_reason', sa.Text(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.Column('auto_reset_daily', sa.Boolean(), nullable=True),
    sa.Column('manual_reset_required', sa.Boolean(), nullable=True),
    sa.Column('last_reset', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_controls_emergency_triggered'), 'emergency_controls', ['emergency_triggered'], unique=False)
    op.create_index(op.f('ix_emergency_controls_id'), 'emergency_controls', ['id'], unique=False)
    op.create_index(op.f('ix_emergency_controls_is_active'), 'emergency_controls', ['is_active'], unique=False)
    op.create_index(op.f('ix_emergency_controls_user_id'), 'emergency_controls', ['user_id'], unique=False)
    op.create_table('trading_audit_trail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=50), nullable=True),
    sa.Column('state_before', sa.JSON(), nullable=True),
    sa.Column('state_after', sa.JSON(), nullable=True),
    sa.Column('triggered_by', sa.String(length=50), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_action_type', 'trading_audit_trail', ['action_type'], unique=False)
    op.create_index('idx_audit_entity', 'trading_audit_trail', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_audit_user_time', 'trading_audit_trail', ['user_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_trading_audit_trail_action_type'), 'trading_audit_trail', ['action_type'], unique=False)
    op.create_index(op.f('ix_trading_audit_trail_entity_id'), 'trading_audit_trail', ['entity_id'], unique=False)
    op.create_index(op.f('ix_trading_audit_trail_entity_type'), 'trading_audit_trail', ['entity_type'], unique=False)
    op.create_index(op.f('ix_trading_audit_trail_id'), 'trading_audit_trail', ['id'], unique=False)
    op.create_index(op.f('ix_trading_audit_trail_timestamp'), 'trading_audit_trail', ['timestamp'], unique=False)
    op.create_index(op.f('ix_trading_audit_trail_user_id'), 'trading_audit_trail', ['user_id'], unique=False)
    op.create_table('trading_system_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_level', sa.String(length=20), nullable=False),
    sa.Column('component', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('trade_id', sa.String(length=50), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('function_name', sa.String(length=100), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('additional_data', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trading_log_level_component', 'trading_system_logs', ['log_level', 'component'], unique=False)
    op.create_index('idx_trading_log_timestamp', 'trading_system_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_trading_system_logs_component'), 'trading_system_logs', ['component'], unique=False)
    op.create_index(op.f('ix_trading_system_logs_id'), 'trading_system_logs', ['id'], unique=False)
    op.create_index(op.f('ix_trading_system_logs_log_level'), 'trading_system_logs', ['log_level'], unique=False)
    op.create_index(op.f('ix_trading_system_logs_timestamp'), 'trading_system_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_trading_system_logs_trade_id'), 'trading_system_logs', ['trade_id'], unique=False)
    op.create_index(op.f('ix_trading_system_logs_user_id'), 'trading_system_logs', ['user_id'], unique=False)
    op.create_table('auto_trade_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('trade_id', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('instrument_key', sa.String(length=100), nullable=False),
    sa.Column('strategy_name', sa.String(length=50), nullable=True),
    sa.Column('signal_type', sa.String(length=10), nullable=False),
    sa.Column('signal_strength', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fibonacci_levels', sa.JSON(), nullable=True),
    sa.Column('ema_values', sa.JSON(), nullable=True),
    sa.Column('swing_high', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('swing_low', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('entry_time', sa.DateTime(), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('entry_order_id', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('lot_size', sa.Integer(), nullable=False),
    sa.Column('exit_time', sa.DateTime(), nullable=True),
    sa.Column('exit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('exit_order_id', sa.String(length=50), nullable=True),
    sa.Column('exit_reason', sa.String(length=50), nullable=True),
    sa.Column('gross_pnl', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('net_pnl', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('pnl_percentage', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('risk_reward_actual', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('initial_stop_loss', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('target_1', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('target_2', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_profit_reached', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_drawdown_in_trade', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('signal_generation_latency_ms', sa.Integer(), nullable=True),
    sa.Column('order_execution_latency_ms', sa.Integer(), nullable=True),
    sa.Column('total_execution_latency_ms', sa.Integer(), nullable=True),
    sa.Column('time_in_trade_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['auto_trading_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_auto_trade_strategy', 'auto_trade_executions', ['strategy_name', 'signal_type'], unique=False)
    op.create_index('idx_auto_trade_symbol_status', 'auto_trade_executions', ['symbol', 'status'], unique=False)
    op.create_index('idx_auto_trade_user_time', 'auto_trade_executions', ['user_id', 'entry_time'], unique=False)
    op.create_index(op.f('ix_auto_trade_executions_entry_time'), 'auto_trade_executions', ['entry_time'], unique=False)
    op.create_index(op.f('ix_auto_trade_executions_id'), 'auto_trade_executions', ['id'], unique=False)
    op.create_index(op.f('ix_auto_trade_executions_status'), 'auto_trade_executions', ['status'], unique=False)
    op.create_index(op.f('ix_auto_trade_executions_symbol'), 'auto_trade_executions', ['symbol'], unique=False)
    op.create_index(op.f('ix_auto_trade_executions_trade_id'), 'auto_trade_executions', ['trade_id'], unique=True)
    op.create_index(op.f('ix_auto_trade_executions_user_id'), 'auto_trade_executions', ['user_id'], unique=False)
    op.create_table('active_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_execution_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('instrument_key', sa.String(length=100), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('current_pnl', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('current_pnl_percentage', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('current_stop_loss', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('trailing_stop_triggered', sa.Boolean(), nullable=True),
    sa.Column('highest_price_reached', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unrealized_risk', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('mark_to_market_time', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trade_execution_id'], ['auto_trade_executions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_execution_id')
    )
    op.create_index('idx_active_position_user_active', 'active_positions', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_active_positions_id'), 'active_positions', ['id'], unique=False)
    op.create_index(op.f('ix_active_positions_is_active'), 'active_positions', ['is_active'], unique=False)
    op.create_index(op.f('ix_active_positions_mark_to_market_time'), 'active_positions', ['mark_to_market_time'], unique=False)
    op.create_index(op.f('ix_active_positions_symbol'), 'active_positions', ['symbol'], unique=False)
    op.create_index(op.f('ix_active_positions_user_id'), 'active_positions', ['user_id'], unique=False)
    op.drop_index('idx_combined_signal_strength', table_name='fibonacci_ema_signals')
    op.drop_index('idx_signal_validity', table_name='fibonacci_ema_signals')
    op.drop_index('idx_symbol_signal_time', table_name='fibonacci_ema_signals')
    op.drop_index('ix_fibonacci_ema_signals_id', table_name='fibonacci_ema_signals')
    op.drop_index('ix_fibonacci_ema_signals_symbol', table_name='fibonacci_ema_signals')
    op.drop_table('fibonacci_ema_signals')
    op.drop_index('idx_exit_signals', table_name='trade_monitoring_logs')
    op.drop_index('idx_trade_monitor_time', table_name='trade_monitoring_logs')
    op.drop_index('idx_user_monitor_time', table_name='trade_monitoring_logs')
    op.drop_index('ix_trade_monitoring_logs_id', table_name='trade_monitoring_logs')
    op.drop_table('trade_monitoring_logs')
    op.drop_index('idx_paper_account_user', table_name='paper_trading_accounts')
    op.drop_index('ix_paper_trading_accounts_id', table_name='paper_trading_accounts')
    op.drop_table('paper_trading_accounts')
    op.drop_index('idx_user_analytics_date', table_name='daily_auto_trading_analytics')
    op.drop_index('ix_daily_auto_trading_analytics_id', table_name='daily_auto_trading_analytics')
    op.drop_table('daily_auto_trading_analytics')
    op.drop_index('ix_auto_trading_configs_id', table_name='auto_trading_configs')
    op.drop_table('auto_trading_configs')
    op.drop_index('idx_option_type_status', table_name='options_trade_executions')
    op.drop_index('idx_trading_mode_session', table_name='options_trade_executions')
    op.drop_index('idx_underlying_symbol_date', table_name='options_trade_executions')
    op.drop_index('ix_options_trade_executions_id', table_name='options_trade_executions')
    op.drop_index('ix_options_trade_executions_underlying_symbol', table_name='options_trade_executions')
    op.drop_table('options_trade_executions')
    op.alter_column('user_trading_config', 'option_strategy',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'ATM_STRADDLE'::character varying"))
    op.create_index('idx_user_trading_config_user_id', 'user_trading_config', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_trading_config_id'), 'user_trading_config', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_trading_config_id'), table_name='user_trading_config')
    op.drop_index('idx_user_trading_config_user_id', table_name='user_trading_config')
    op.alter_column('user_trading_config', 'option_strategy',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'ATM_STRADDLE'::character varying"))
    op.create_table('options_trade_executions',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('options_trade_executions_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('underlying_symbol', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('option_symbol', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('option_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('strike_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('expiry_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('trade_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('entry_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('exit_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('entry_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('exit_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('strategy_signals', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('stop_loss_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('target_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('trailing_stop_loss', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('delta_entry', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('gamma_entry', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('theta_entry', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('vega_entry', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('iv_entry', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('delta_exit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('gamma_exit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('theta_exit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('vega_exit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('iv_exit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('pnl', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('pnl_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('commission', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('exit_reason', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('trading_mode', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('market_sentiment', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('execution_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['auto_trading_sessions.id'], name='options_trade_executions_session_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='options_trade_executions_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='options_trade_executions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_options_trade_executions_underlying_symbol', 'options_trade_executions', ['underlying_symbol'], unique=False)
    op.create_index('ix_options_trade_executions_id', 'options_trade_executions', ['id'], unique=False)
    op.create_index('idx_underlying_symbol_date', 'options_trade_executions', ['underlying_symbol', 'entry_time'], unique=False)
    op.create_index('idx_trading_mode_session', 'options_trade_executions', ['trading_mode', 'session_id'], unique=False)
    op.create_index('idx_option_type_status', 'options_trade_executions', ['option_type', 'status'], unique=False)
    op.create_table('auto_trading_configs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('default_trading_mode', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('auto_start_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('market_open_delay_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_stocks_per_day', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('min_volume_threshold', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('min_price_change_threshold', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('excluded_sectors', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('max_position_size_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('max_daily_loss_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('stop_loss_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('target_profit_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('trailing_stop_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fibonacci_lookback_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ema_short_period', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ema_medium_period', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ema_long_period', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('signal_confluence_required', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('max_trade_duration_hours', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('time_based_exit_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('theta_decay_exit_threshold', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('trade_execution_notifications', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('exit_signal_notifications', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('daily_summary_notifications', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('kill_switch_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('kill_switch_daily_loss_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('kill_switch_consecutive_losses', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('paper_trading_capital', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('live_trading_capital_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='auto_trading_configs_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='auto_trading_configs_pkey'),
    sa.UniqueConstraint('user_id', name='auto_trading_configs_user_id_key')
    )
    op.create_index('ix_auto_trading_configs_id', 'auto_trading_configs', ['id'], unique=False)
    op.create_table('daily_auto_trading_analytics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('analytics_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('stocks_screened', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stocks_selected', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('selection_accuracy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sector_performance', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('best_performing_sector', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('worst_performing_sector', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('total_trades_executed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_trades_closed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('winning_trades', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('losing_trades', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_pnl', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_pnl_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('gross_profit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('gross_loss', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('net_profit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('win_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('profit_factor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('average_win', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('average_loss', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('risk_reward_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fibonacci_signal_accuracy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ema_signal_accuracy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('combined_signal_accuracy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('max_drawdown', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('max_consecutive_losses', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('largest_loss', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('largest_win', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('average_trade_duration_minutes', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fastest_trade_duration_minutes', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('slowest_trade_duration_minutes', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('average_delta_at_entry', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('average_theta_impact', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('average_iv_at_entry', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('market_sentiment', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('market_volatility', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('market_trend', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('signal_processing_time_avg_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('trade_execution_time_avg_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('monitoring_update_frequency_seconds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('starting_capital', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ending_capital', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('capital_utilization_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='daily_auto_trading_analytics_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='daily_auto_trading_analytics_pkey'),
    sa.UniqueConstraint('user_id', 'analytics_date', name='unique_user_daily_analytics')
    )
    op.create_index('ix_daily_auto_trading_analytics_id', 'daily_auto_trading_analytics', ['id'], unique=False)
    op.create_index('idx_user_analytics_date', 'daily_auto_trading_analytics', ['user_id', 'analytics_date'], unique=False)
    op.create_table('paper_trading_accounts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('initial_balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('total_pnl', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('realized_pnl', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('unrealized_pnl', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('total_trades', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('winning_trades', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('losing_trades', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('max_drawdown', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('max_balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('last_reset_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='paper_trading_accounts_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='paper_trading_accounts_pkey'),
    sa.UniqueConstraint('user_id', name='unique_user_paper_account')
    )
    op.create_index('ix_paper_trading_accounts_id', 'paper_trading_accounts', ['id'], unique=False)
    op.create_index('idx_paper_account_user', 'paper_trading_accounts', ['user_id'], unique=False)
    op.create_table('trade_monitoring_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('monitor_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('current_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('current_pnl', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('current_pnl_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('time_to_expiry_hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('theta_decay_impact', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('implied_volatility', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('delta', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fibonacci_level_hit', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('ema_crossover_detected', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('support_resistance_test', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('new_trailing_sl', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('trailing_sl_updated', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('exit_signal_generated', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('exit_signal_type', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('exit_signal_strength', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('max_favorable_excursion', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('max_adverse_excursion', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('processing_time_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['trade_id'], ['options_trade_executions.id'], name='trade_monitoring_logs_trade_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='trade_monitoring_logs_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='trade_monitoring_logs_pkey')
    )
    op.create_index('ix_trade_monitoring_logs_id', 'trade_monitoring_logs', ['id'], unique=False)
    op.create_index('idx_user_monitor_time', 'trade_monitoring_logs', ['user_id', 'monitor_time'], unique=False)
    op.create_index('idx_trade_monitor_time', 'trade_monitoring_logs', ['trade_id', 'monitor_time'], unique=False)
    op.create_index('idx_exit_signals', 'trade_monitoring_logs', ['exit_signal_generated', 'exit_signal_type'], unique=False)
    op.create_table('fibonacci_ema_signals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('instrument_key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('signal_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('current_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('previous_close', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('high_24h', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('low_24h', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('fib_23_6', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fib_38_2', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fib_50_0', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fib_61_8', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fib_78_6', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ema_9', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ema_21', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ema_50', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ema_200', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fibonacci_signal', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('ema_signal', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('combined_signal', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('signal_strength', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('fib_ema_confluence', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('resistance_level', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('support_level', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('volume_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('momentum_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('volatility_index', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_valid', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('expiry_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('calculation_time_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='fibonacci_ema_signals_pkey')
    )
    op.create_index('ix_fibonacci_ema_signals_symbol', 'fibonacci_ema_signals', ['symbol'], unique=False)
    op.create_index('ix_fibonacci_ema_signals_id', 'fibonacci_ema_signals', ['id'], unique=False)
    op.create_index('idx_symbol_signal_time', 'fibonacci_ema_signals', ['symbol', 'signal_time'], unique=False)
    op.create_index('idx_signal_validity', 'fibonacci_ema_signals', ['is_valid', 'expiry_time'], unique=False)
    op.create_index('idx_combined_signal_strength', 'fibonacci_ema_signals', ['combined_signal', 'signal_strength'], unique=False)
    op.drop_index(op.f('ix_active_positions_user_id'), table_name='active_positions')
    op.drop_index(op.f('ix_active_positions_symbol'), table_name='active_positions')
    op.drop_index(op.f('ix_active_positions_mark_to_market_time'), table_name='active_positions')
    op.drop_index(op.f('ix_active_positions_is_active'), table_name='active_positions')
    op.drop_index(op.f('ix_active_positions_id'), table_name='active_positions')
    op.drop_index('idx_active_position_user_active', table_name='active_positions')
    op.drop_table('active_positions')
    op.drop_index(op.f('ix_auto_trade_executions_user_id'), table_name='auto_trade_executions')
    op.drop_index(op.f('ix_auto_trade_executions_trade_id'), table_name='auto_trade_executions')
    op.drop_index(op.f('ix_auto_trade_executions_symbol'), table_name='auto_trade_executions')
    op.drop_index(op.f('ix_auto_trade_executions_status'), table_name='auto_trade_executions')
    op.drop_index(op.f('ix_auto_trade_executions_id'), table_name='auto_trade_executions')
    op.drop_index(op.f('ix_auto_trade_executions_entry_time'), table_name='auto_trade_executions')
    op.drop_index('idx_auto_trade_user_time', table_name='auto_trade_executions')
    op.drop_index('idx_auto_trade_symbol_status', table_name='auto_trade_executions')
    op.drop_index('idx_auto_trade_strategy', table_name='auto_trade_executions')
    op.drop_table('auto_trade_executions')
    op.drop_index(op.f('ix_trading_system_logs_user_id'), table_name='trading_system_logs')
    op.drop_index(op.f('ix_trading_system_logs_trade_id'), table_name='trading_system_logs')
    op.drop_index(op.f('ix_trading_system_logs_timestamp'), table_name='trading_system_logs')
    op.drop_index(op.f('ix_trading_system_logs_log_level'), table_name='trading_system_logs')
    op.drop_index(op.f('ix_trading_system_logs_id'), table_name='trading_system_logs')
    op.drop_index(op.f('ix_trading_system_logs_component'), table_name='trading_system_logs')
    op.drop_index('idx_trading_log_timestamp', table_name='trading_system_logs')
    op.drop_index('idx_trading_log_level_component', table_name='trading_system_logs')
    op.drop_table('trading_system_logs')
    op.drop_index(op.f('ix_trading_audit_trail_user_id'), table_name='trading_audit_trail')
    op.drop_index(op.f('ix_trading_audit_trail_timestamp'), table_name='trading_audit_trail')
    op.drop_index(op.f('ix_trading_audit_trail_id'), table_name='trading_audit_trail')
    op.drop_index(op.f('ix_trading_audit_trail_entity_type'), table_name='trading_audit_trail')
    op.drop_index(op.f('ix_trading_audit_trail_entity_id'), table_name='trading_audit_trail')
    op.drop_index(op.f('ix_trading_audit_trail_action_type'), table_name='trading_audit_trail')
    op.drop_index('idx_audit_user_time', table_name='trading_audit_trail')
    op.drop_index('idx_audit_entity', table_name='trading_audit_trail')
    op.drop_index('idx_audit_action_type', table_name='trading_audit_trail')
    op.drop_table('trading_audit_trail')
    op.drop_index(op.f('ix_emergency_controls_user_id'), table_name='emergency_controls')
    op.drop_index(op.f('ix_emergency_controls_is_active'), table_name='emergency_controls')
    op.drop_index(op.f('ix_emergency_controls_id'), table_name='emergency_controls')
    op.drop_index(op.f('ix_emergency_controls_emergency_triggered'), table_name='emergency_controls')
    op.drop_table('emergency_controls')
    op.drop_index(op.f('ix_daily_trading_performance_trading_date'), table_name='daily_trading_performance')
    op.drop_index(op.f('ix_daily_trading_performance_id'), table_name='daily_trading_performance')
    op.drop_index('idx_daily_perf_date', table_name='daily_trading_performance')
    op.drop_table('daily_trading_performance')
    # ### end Alembic commands ###
