"""add_fund_ledger_system

Revision ID: a62763117ed4
Revises: 762a64d64b9d
Create Date: 2026-02-25 16:21:58.440948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a62763117ed4'
down_revision: Union[str, None] = '762a64d64b9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fund_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trading_mode', sa.String(length=20), nullable=False),
    sa.Column('transaction_type', sa.String(length=10), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('balance_before', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('reference_id', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ledger_user_mode', 'fund_ledger', ['user_id', 'trading_mode'], unique=False)
    op.create_index(op.f('ix_fund_ledger_category'), 'fund_ledger', ['category'], unique=False)
    op.create_index(op.f('ix_fund_ledger_id'), 'fund_ledger', ['id'], unique=False)
    op.create_index(op.f('ix_fund_ledger_reference_id'), 'fund_ledger', ['reference_id'], unique=False)
    op.create_index(op.f('ix_fund_ledger_timestamp'), 'fund_ledger', ['timestamp'], unique=False)
    op.create_index(op.f('ix_fund_ledger_trading_mode'), 'fund_ledger', ['trading_mode'], unique=False)
    op.create_index(op.f('ix_fund_ledger_user_id'), 'fund_ledger', ['user_id'], unique=False)
    op.drop_index('idx_trading_log_level_component', table_name='trading_system_logs')
    op.drop_index('idx_trading_log_timestamp', table_name='trading_system_logs')
    op.drop_index('ix_trading_system_logs_component', table_name='trading_system_logs')
    op.drop_index('ix_trading_system_logs_id', table_name='trading_system_logs')
    op.drop_index('ix_trading_system_logs_log_level', table_name='trading_system_logs')
    op.drop_index('ix_trading_system_logs_timestamp', table_name='trading_system_logs')
    op.drop_index('ix_trading_system_logs_trade_id', table_name='trading_system_logs')
    op.drop_index('ix_trading_system_logs_user_id', table_name='trading_system_logs')
    op.drop_table('trading_system_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trading_system_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('log_level', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('component', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('trade_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('symbol', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('latency_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('function_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('line_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stack_trace', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('additional_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='trading_system_logs_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='trading_system_logs_pkey')
    )
    op.create_index('ix_trading_system_logs_user_id', 'trading_system_logs', ['user_id'], unique=False)
    op.create_index('ix_trading_system_logs_trade_id', 'trading_system_logs', ['trade_id'], unique=False)
    op.create_index('ix_trading_system_logs_timestamp', 'trading_system_logs', ['timestamp'], unique=False)
    op.create_index('ix_trading_system_logs_log_level', 'trading_system_logs', ['log_level'], unique=False)
    op.create_index('ix_trading_system_logs_id', 'trading_system_logs', ['id'], unique=False)
    op.create_index('ix_trading_system_logs_component', 'trading_system_logs', ['component'], unique=False)
    op.create_index('idx_trading_log_timestamp', 'trading_system_logs', ['timestamp'], unique=False)
    op.create_index('idx_trading_log_level_component', 'trading_system_logs', ['log_level', 'component'], unique=False)
    op.drop_index(op.f('ix_fund_ledger_user_id'), table_name='fund_ledger')
    op.drop_index(op.f('ix_fund_ledger_trading_mode'), table_name='fund_ledger')
    op.drop_index(op.f('ix_fund_ledger_timestamp'), table_name='fund_ledger')
    op.drop_index(op.f('ix_fund_ledger_reference_id'), table_name='fund_ledger')
    op.drop_index(op.f('ix_fund_ledger_id'), table_name='fund_ledger')
    op.drop_index(op.f('ix_fund_ledger_category'), table_name='fund_ledger')
    op.drop_index('idx_ledger_user_mode', table_name='fund_ledger')
    op.drop_table('fund_ledger')
    # ### end Alembic commands ###
