"""add_otp_type_field

Revision ID: c92de86e1712
Revises: 796cb6171601
Create Date: 2025-05-24 23:55:18.504731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c92de86e1712'
down_revision: Union[str, None] = '796cb6171601'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_codes', sa.Column('otp_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('otp_codes', 'otp_type')
    # ### end Alembic commands ###
