"""your migration message

Revision ID: cea74a18a738
Revises: 7ddbb769ef69
Create Date: 2025-08-29 22:02:22.949422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cea74a18a738'
down_revision: Union[str, None] = '7ddbb769ef69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_trading_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('initial_capital', sa.Float(), nullable=False),
    sa.Column('current_balance', sa.Float(), nullable=False),
    sa.Column('used_margin', sa.Float(), nullable=False),
    sa.Column('available_margin', sa.Float(), nullable=False),
    sa.Column('total_pnl', sa.Float(), nullable=False),
    sa.Column('daily_pnl', sa.Float(), nullable=False),
    sa.Column('positions_count', sa.Integer(), nullable=False),
    sa.Column('max_positions', sa.Integer(), nullable=False),
    sa.Column('max_risk_per_trade', sa.Float(), nullable=False),
    sa.Column('max_daily_loss', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_paper_trading_accounts_id'), 'paper_trading_accounts', ['id'], unique=False)
    op.create_table('paper_trading_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('instrument_key', sa.String(), nullable=False),
    sa.Column('option_type', sa.String(), nullable=False),
    sa.Column('strike_price', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('lot_size', sa.Integer(), nullable=False),
    sa.Column('invested_amount', sa.Float(), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=False),
    sa.Column('pnl', sa.Float(), nullable=False),
    sa.Column('pnl_percentage', sa.Float(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('target', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['paper_trading_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_trading_positions_id'), 'paper_trading_positions', ['id'], unique=False)
    op.create_index(op.f('ix_paper_trading_positions_position_id'), 'paper_trading_positions', ['position_id'], unique=True)
    op.create_table('paper_trading_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('pnl_percentage', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['paper_trading_accounts.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['paper_trading_positions.position_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_trading_history_id'), 'paper_trading_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paper_trading_history_id'), table_name='paper_trading_history')
    op.drop_table('paper_trading_history')
    op.drop_index(op.f('ix_paper_trading_positions_position_id'), table_name='paper_trading_positions')
    op.drop_index(op.f('ix_paper_trading_positions_id'), table_name='paper_trading_positions')
    op.drop_table('paper_trading_positions')
    op.drop_index(op.f('ix_paper_trading_accounts_id'), table_name='paper_trading_accounts')
    op.drop_table('paper_trading_accounts')
    # ### end Alembic commands ###
