"""Add trading_mode to AutoTradingSession

Revision ID: cf6126e17b1b
Revises: 79dde23b4507
Create Date: 2025-10-05 12:43:51.593294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = 'cf6126e17b1b'
down_revision: Union[str, None] = '79dde23b4507'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = inspect(conn)

    # 1. Handle auto_trading_sessions
    if inspector.has_table("auto_trading_sessions"):
        ats_columns = [c['name'] for c in inspector.get_columns('auto_trading_sessions')]
        if 'trading_mode' not in ats_columns:
            op.add_column('auto_trading_sessions', sa.Column('trading_mode', sa.String(length=20), nullable=True))
            # Check for index existence before creating
            indexes = [i['name'] for i in inspector.get_indexes('auto_trading_sessions')]
            if op.f('ix_auto_trading_sessions_trading_mode') not in indexes and 'ix_auto_trading_sessions_trading_mode' not in indexes:
                op.create_index(op.f('ix_auto_trading_sessions_trading_mode'), 'auto_trading_sessions', ['trading_mode'], unique=False)

    # 2. Handle selected_stocks
    if not inspector.has_table("selected_stocks"):
        # Create table if it doesn't exist (Ghost migration recovery)
        op.create_table(
            "selected_stocks",
            sa.Column("id", sa.Integer(), nullable=False, primary_key=True),
            sa.Column("symbol", sa.String(50), nullable=False, index=True),
            sa.Column("instrument_key", sa.String(100), nullable=False),
            sa.Column("selection_date", sa.Date(), nullable=False, index=True),
            sa.Column("selection_score", sa.Float(), nullable=False),
            sa.Column("selection_reason", sa.String(100), nullable=False),
            sa.Column("price_at_selection", sa.Float(), nullable=False),
            sa.Column("volume_at_selection", sa.Integer(), default=0),
            sa.Column("change_percent_at_selection", sa.Float(), default=0.0),
            sa.Column("sector", sa.String(50), default="OTHER"),
            sa.Column("score_breakdown", sa.Text()),
            # New columns from this migration included in creation
            sa.Column('market_sentiment', sa.String(length=20), nullable=True),
            sa.Column('market_sentiment_confidence', sa.Float(), nullable=True),
            sa.Column('advance_decline_ratio', sa.Float(), nullable=True),
            sa.Column('market_breadth_percent', sa.Float(), nullable=True),
            sa.Column('advancing_stocks', sa.Integer(), nullable=True),
            sa.Column('declining_stocks', sa.Integer(), nullable=True),
            sa.Column('total_stocks_analyzed', sa.Integer(), nullable=True),
            sa.Column('selection_phase', sa.String(length=30), nullable=True),
            # Rest of original schema
            sa.Column("is_active", sa.Boolean(), default=True),
            sa.Column("option_type", sa.String()),
            sa.Column("option_contract", sa.Text()),
            sa.Column("option_contracts_available", sa.Integer(), default=0),
            sa.Column("option_chain_data", sa.Text()),
            sa.Column("option_expiry_date", sa.String()),
            sa.Column("option_expiry_dates", sa.Text()),
            sa.Column("max_price_achieved", sa.Float()),
            sa.Column("min_price_achieved", sa.Float()),
            sa.Column("exit_price", sa.Float()),
            sa.Column("exit_reason", sa.String(100)),
            sa.Column("created_at", sa.DateTime(), server_default=sa.func.now()),
            sa.Column("updated_at", sa.DateTime(), server_default=sa.func.now(), onupdate=sa.func.now()),
        )
        # Indexes for selected_stocks
        op.create_index("idx_symbol_selection_date", "selected_stocks", ["symbol", "selection_date"])
        op.create_index("idx_selection_date_active", "selected_stocks", ["selection_date", "is_active"])
        op.create_index("idx_selection_score", "selected_stocks", ["selection_score"])
    else:
        # Table exists, ensure columns exist
        ss_columns = [c['name'] for c in inspector.get_columns('selected_stocks')]
        
        if 'market_sentiment' not in ss_columns:
            op.add_column('selected_stocks', sa.Column('market_sentiment', sa.String(length=20), nullable=True))
        if 'market_sentiment_confidence' not in ss_columns:
            op.add_column('selected_stocks', sa.Column('market_sentiment_confidence', sa.Float(), nullable=True))
        if 'advance_decline_ratio' not in ss_columns:
            op.add_column('selected_stocks', sa.Column('advance_decline_ratio', sa.Float(), nullable=True))
        if 'market_breadth_percent' not in ss_columns:
            op.add_column('selected_stocks', sa.Column('market_breadth_percent', sa.Float(), nullable=True))
        if 'advancing_stocks' not in ss_columns:
            op.add_column('selected_stocks', sa.Column('advancing_stocks', sa.Integer(), nullable=True))
        if 'declining_stocks' not in ss_columns:
            op.add_column('selected_stocks', sa.Column('declining_stocks', sa.Integer(), nullable=True))
        if 'total_stocks_analyzed' not in ss_columns:
            op.add_column('selected_stocks', sa.Column('total_stocks_analyzed', sa.Integer(), nullable=True))
        if 'selection_phase' not in ss_columns:
            op.add_column('selected_stocks', sa.Column('selection_phase', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE selected_stocks DROP COLUMN IF EXISTS selection_phase')
    op.execute('ALTER TABLE selected_stocks DROP COLUMN IF EXISTS total_stocks_analyzed')
    op.execute('ALTER TABLE selected_stocks DROP COLUMN IF EXISTS declining_stocks')
    op.execute('ALTER TABLE selected_stocks DROP COLUMN IF EXISTS advancing_stocks')
    op.execute('ALTER TABLE selected_stocks DROP COLUMN IF EXISTS market_breadth_percent')
    op.execute('ALTER TABLE selected_stocks DROP COLUMN IF EXISTS advance_decline_ratio')
    op.execute('ALTER TABLE selected_stocks DROP COLUMN IF EXISTS market_sentiment_confidence')
    op.execute('ALTER TABLE selected_stocks DROP COLUMN IF EXISTS market_sentiment')
    
    op.execute('DROP INDEX IF EXISTS ix_auto_trading_sessions_trading_mode')
    op.execute('ALTER TABLE auto_trading_sessions DROP COLUMN IF EXISTS trading_mode')
    # ### end Alembic commands ###
