"""Add trading_mode to AutoTradingSession

Revision ID: cf6126e17b1b
Revises: 79dde23b4507
Create Date: 2025-10-05 12:43:51.593294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf6126e17b1b'
down_revision: Union[str, None] = '79dde23b4507'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auto_trading_sessions', sa.Column('trading_mode', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_auto_trading_sessions_trading_mode'), 'auto_trading_sessions', ['trading_mode'], unique=False)
    op.add_column('selected_stocks', sa.Column('market_sentiment', sa.String(length=20), nullable=True))
    op.add_column('selected_stocks', sa.Column('market_sentiment_confidence', sa.Float(), nullable=True))
    op.add_column('selected_stocks', sa.Column('advance_decline_ratio', sa.Float(), nullable=True))
    op.add_column('selected_stocks', sa.Column('market_breadth_percent', sa.Float(), nullable=True))
    op.add_column('selected_stocks', sa.Column('advancing_stocks', sa.Integer(), nullable=True))
    op.add_column('selected_stocks', sa.Column('declining_stocks', sa.Integer(), nullable=True))
    op.add_column('selected_stocks', sa.Column('total_stocks_analyzed', sa.Integer(), nullable=True))
    op.add_column('selected_stocks', sa.Column('selection_phase', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('selected_stocks', 'selection_phase')
    op.drop_column('selected_stocks', 'total_stocks_analyzed')
    op.drop_column('selected_stocks', 'declining_stocks')
    op.drop_column('selected_stocks', 'advancing_stocks')
    op.drop_column('selected_stocks', 'market_breadth_percent')
    op.drop_column('selected_stocks', 'advance_decline_ratio')
    op.drop_column('selected_stocks', 'market_sentiment_confidence')
    op.drop_column('selected_stocks', 'market_sentiment')
    op.drop_index(op.f('ix_auto_trading_sessions_trading_mode'), table_name='auto_trading_sessions')
    op.drop_column('auto_trading_sessions', 'trading_mode')
    # ### end Alembic commands ###
