"""add_notifications_tables

Revision ID: f06e34fd3062
Revises: c0c95bf359e1
Create Date: 2025-06-03 23:37:03.455695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f06e34fd3062'
down_revision: Union[str, None] = 'c0c95bf359e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto_trading_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('selected_stocks', sa.JSON(), nullable=False),
    sa.Column('screening_config', sa.JSON(), nullable=True),
    sa.Column('stocks_screened', sa.Integer(), nullable=True),
    sa.Column('session_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('successful_trades', sa.Integer(), nullable=True),
    sa.Column('failed_trades', sa.Integer(), nullable=True),
    sa.Column('session_pnl', sa.Float(), nullable=True),
    sa.Column('start_capital', sa.Float(), nullable=True),
    sa.Column('end_capital', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auto_trading_sessions_id'), 'auto_trading_sessions', ['id'], unique=False)
    op.create_table('daily_trading_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('stocks_selected', sa.JSON(), nullable=False),
    sa.Column('trades_executed', sa.Integer(), nullable=True),
    sa.Column('daily_pnl', sa.Float(), nullable=True),
    sa.Column('winning_trades', sa.Integer(), nullable=True),
    sa.Column('losing_trades', sa.Integer(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('portfolio_value', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('best_trade_pnl', sa.Float(), nullable=True),
    sa.Column('worst_trade_pnl', sa.Float(), nullable=True),
    sa.Column('avg_trade_duration', sa.Float(), nullable=True),
    sa.Column('total_commissions', sa.Float(), nullable=True),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('auto_generated', sa.Boolean(), nullable=True),
    sa.Column('report_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['auto_trading_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_trading_reports_id'), 'daily_trading_reports', ['id'], unique=False)
    op.create_table('trade_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('trade_type', sa.String(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('entry_time', sa.DateTime(), nullable=True),
    sa.Column('exit_time', sa.DateTime(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('pnl_percentage', sa.Float(), nullable=True),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('exit_reason', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('technical_indicators', sa.JSON(), nullable=True),
    sa.Column('execution_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['auto_trading_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_executions_id'), 'trade_executions', ['id'], unique=False)
    op.add_column('notifications', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('notifications', sa.Column('priority', sa.String(length=20), nullable=True))
    op.add_column('notifications', sa.Column('category', sa.String(length=50), nullable=True))
    op.add_column('notifications', sa.Column('is_read', sa.Boolean(), nullable=True))
    op.alter_column('notifications', 'message',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.execute('ALTER TABLE notifications DROP COLUMN IF EXISTS "read"')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('read', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('notifications', 'message',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('notifications', 'is_read')
    op.drop_column('notifications', 'category')
    op.drop_column('notifications', 'priority')
    op.drop_column('notifications', 'title')
    op.drop_index(op.f('ix_trade_executions_id'), table_name='trade_executions')
    op.drop_table('trade_executions')
    op.drop_index(op.f('ix_daily_trading_reports_id'), table_name='daily_trading_reports')
    op.drop_table('daily_trading_reports')
    op.drop_index(op.f('ix_auto_trading_sessions_id'), table_name='auto_trading_sessions')
    op.drop_table('auto_trading_sessions')
    # ### end Alembic commands ###
